# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: RL book reproduction
email: sunmr2017@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 Reference book:Reinforcement Learning book, 2nd edition, by Richard S. Sutton, Andrew G. Barto
baseurl: "/RL_reproduce_notes_newTheme" # the subpath of your site, e.g. /blog
url: "https://licccccs.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: hha
github_username:  liCCcccs

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
markdown: kramdown
mathjax: true

paginate: 5 # amount of posts to show
paginate_path: /page:num/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      search: true
      read_time: false
      words_per_minute: 100
      comments: true
      share: true
      related: true
      author_profile: true
      sidebar:
              nav: "docs"



author:
  name: "Lily"
  avatar: "/files/other/head/Screenshot2.png"
  bio: " I am Lily :D" # Note: Markdown is allowed
  location: "Somewhere on ..."
  links:
    - label: "Made Mistakes"
      icon: "fas fa-fw fa-link"
      url: "https://mademistakes.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mmistakes"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/liCCcccs"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://instagram.com/mmistakes"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
